### ISSUE TITLE
Deploy On Maven Central

### ISSUE THREAD

**Issue by gsdenys** [diosmosis/junit-composite-runner#1]
Hi, 

That's a cool project. Why didn't you had not deployed it on maven central repository?

Thanks

**Comment by diosmosis** [comment]
I wrote it to try and use robolectric with another test runner, but the approach doesn't work with robolectric, so I just forgot about it :). I can put it up on maven central this weekend.

**Comment by gsdenys** [comment]
Show!! I will wainting for!!

**Comment by diosmosis** [comment]
Put it up on maven central, see here: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22junit-composite-runner%22

This is about the most support I can give for this project.
